config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'items#index'
  resources :items do
    collection do
      get :multiplex
    end
  end

  get :all_items, to: 'items#all_items'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id         :integer          not null, primary key
#  first_name :string(255)
#  last_name  :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null

class Artist < ApplicationRecord
  has_many :items, dependent: :destroy

  def full_name
    [first_name, last_name].compact.join(' ')
  end
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  image_url   :string(255)
#  artist_id   :integer 
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_items_on_artist_id

class Item < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = GraphqlSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue StandardError => e
    raise e unless Rails.env.development?
    handle_error_in_development(e)
  end

  private

  # Handle variables in form data, JSON body, or a blank value
  def prepare_variables(variables_param)
    case variables_param
    when String
      if variables_param.present?
        JSON.parse(variables_param) || {}
      else
        {}
      end
    when Hash
      variables_param
    when ActionController::Parameters
      variables_param.to_unsafe_hash # GraphQL-Ruby will validate name and type of incoming variables.
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{variables_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { errors: [{ message: e.message, backtrace: e.backtrace }], data: {} }, status: 500
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = GraphqlSchema.execute(items_query_string, variables: {}, operation_name: nil, context: {}).dig('data', 'items')
  end

  def all_items
    @items = Item.all
  end

  def show
    query_string = 'query getItem($itemId: ID!) {
                      item(id: $itemId) {
                        id
                        title
                        description
                        artist {
                          fullName
                          email
                        }
                      }
                    }'
    variables = { 'itemId' => params[:id] }
    @item = GraphqlSchema.execute(query_string, variables: variables).dig('data', 'item')
  end

  def new
    @item = Item.new
  end

  def create
    item_params = params[:item]
    item_params = "title: \"#{item_params[:title]}\",
                   description: \"#{item_params[:description]}\",
                   imageUrl: \"#{item_params[:image_url].blank? ? Item.first&.image_url : item_params[:image_url]}\",
                   artistId: #{item_params[:artist_id] || Artist.first&.id}"

    query_string = "mutation {
                      createItem(#{item_params}) {
                        id
                        title
                        description
                        imageUrl
                        artistId
                      }
                    }"

    GraphqlSchema.execute(query_string)
    redirect_to items_path
  end

  def destroy
    id = params[:id]
    query_string = "mutation {
                      destroyItem(id: #{id}) {
                        id
                        title
                        description
                        imageUrl
                        artistId
                      }
                    }"

    item = GraphqlSchema.execute(query_string)
    redirect_to items_path
  end

  def edit
    @item = Item.find_by(id: params[:id])
  end

  def update
    item = Item.find_by(id: params[:id])
    item_params = params[:item]
    item_params = "title: \"#{item_params[:title]}\",
                   description: \"#{item_params[:description]}\",
                   imageUrl: \"#{item_params[:image_url]}\""

    query_string = "mutation {
                      updateItem(id: #{params[:id]}, #{item_params}) {
                        id
                        title
                        description
                        imageUrl
                        artistId
                      }
                    }"

    GraphqlSchema.execute(query_string)
    redirect_to item_path(item)
  end

  def multiplex
    artists_query_string = '{
                             artists {
                               id
                               email
                               fullName
                             }
                           }'

    res = GraphqlSchema.multiplex([
            {query: items_query_string},
            {query: artists_query_string},
          ])
    @items = res[0].dig('data', 'items')
    @artists = res[1].dig('data', 'artists')
  end

  private

  def items_query_string
    '{
      items {
        id
        title
        description
        imageUrl
        artist {
          fullName
          email
        }
      }
    }'
  end

  # def item_params
  #   params.require(:item).permit(:title, :description, :image_url, :artist_id)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<p><b>Title: </b><%= f.text_field :title %></p>
<p><b>Description: </b><%= f.text_field :description %></p>
<p><b>Image URL: </b><%= f.text_field :image_url %></p>
<%= f.submit "#{action} Item" %>

app/views/items/_items.html.erb
<hr/>
<br/>
<%= render 'items_form' %>
<hr/>
<%= link_to 'Create Item', new_item_path %>
<hr/>
<%= link_to 'Multiplex', multiplex_items_path %>

app/views/items/_items_form.html.erb
<% @items.each do |item| %>
  <% item_id = item['id'] || item.id
     item_title = item['title'] || item.title %>
  <p><b>Item #<%= item_id %>: </b><%= link_to item_title, item_path(id: item_id) %> <%= link_to 'Edit', edit_item_path(id: item_id) %></p>
  <p><%= item['description'] || item.description %></p>
  <p><%= item['imageUrl'] || item.image_url %></p>
  <p><b>Artist: </b>
    <% if item['artist'] %>
      <% item['artist'].each do |k, v| %>
        <%= "#{v}," %>
      <% end %>
    <% else %>
      <%= "#{item.artist.full_name}, #{item.artist.email}" %>
    <% end %>
  </p>
  <br/>
<% end %>

app/views/items/all_items.html.erb
<%= render 'items' %>

app/views/items/edit.html.erb
<h3>Edit Item</h3>

<%= form_for @item, method: :put do |f| %>
  <%= render 'form', f: f, action: 'Update' %> 
<% end %>

app/views/items/index.html.erb
<hr/>
<br/>
<%= render 'items_form' %>
<hr/>
<%= link_to 'Create Item', new_item_path %>
<hr/>
<%= link_to 'Multiplex', multiplex_items_path %>

app/views/items/multiplex.html.erb
<h3>Multiplex test</h3>
<hr/>
<h4>Items</h4>
<%= render 'items_form' %>
<hr/>
<h4>Artists</h4>
<% @artists.each do |artist| %>
  <p><b>Artist #<%= artist['id'] %>: </b><%= artist['fullName'] %></p>
  <p><%= artist['email'] %></p>
  <br/>
<% end %>

app/views/items/new.html.erb
<h3>New Item</h3>

<%= form_for @item do |f| %>
  <%= render 'form', f: f, action: 'Create' %>
<% end %>

app/views/items/show.html.erb
<p><b>Item #<%= @item['id'] %> Title: </b><%= @item['title'] %></p>
<p><b>Description: </b><%= @item['description'] %></p>
<hr/>
<p><b>Artist: </b>
  <% @item['artist'].each do |k, v| %>
    <%= "#{k}: #{v}," %>
  <% end %>
</p>

<%= link_to 'Delete item', @item, method: :delete, data: { confirm: 'Are you sure?' } %>
<br/><br/>
<%= link_to 'All items', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Graphql</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>